apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hlc5
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-hlc5@sha256:e4456f96c1ab72b61709cf0c4b7f98f26a87eb7d06c25c1573dc12d1502d86c4
        name: my-nodejs
        resources: {}
status: {}
